/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yinchao_media_recoder_YCAudioRecoder */

#ifndef _Included_com_yinchao_media_recoder_YCAudioRecoder
#define _Included_com_yinchao_media_recoder_YCAudioRecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yinchao_media_recoder_YCAudioRecoder
 * Method:    initRecord
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCAudioRecoder_initRecord
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_yinchao_media_recoder_YCAudioRecoder
 * Method:    startRecord
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCAudioRecoder_startRecord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yinchao_media_recoder_YCAudioRecoder
 * Method:    stopRecord
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCAudioRecoder_stopRecord
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
