F_SRC = $(top_srcdir)/freeverb
FV3_SRC = \
	$(F_SRC)/allpass.cpp \
	$(F_SRC)/allpass.hpp \
	$(F_SRC)/allpass_t.hpp \
	$(F_SRC)/biquad.cpp \
	$(F_SRC)/biquad.hpp \
	$(F_SRC)/biquad_t.hpp \
	$(F_SRC)/blockDelay.cpp \
	$(F_SRC)/blockDelay.hpp \
	$(F_SRC)/blockDelay_t.hpp \
	$(F_SRC)/comb.cpp \
	$(F_SRC)/comb.hpp \
	$(F_SRC)/comb_t.hpp \
	$(F_SRC)/compmodel.cpp \
	$(F_SRC)/compmodel.hpp \
	$(F_SRC)/compmodel_t.hpp \
	$(F_SRC)/delay.cpp \
	$(F_SRC)/delay.hpp \
	$(F_SRC)/delay_t.hpp \
	$(F_SRC)/efilter.cpp \
	$(F_SRC)/efilter.hpp \
	$(F_SRC)/efilter_t.hpp \
	$(F_SRC)/fir3bandsplit.cpp \
	$(F_SRC)/fir3bandsplit.hpp \
	$(F_SRC)/fir3bandsplit_t.hpp \
	$(F_SRC)/firfilter.cpp \
	$(F_SRC)/firfilter.hpp \
	$(F_SRC)/firfilter_t.hpp \
	$(F_SRC)/firwindow.cpp \
	$(F_SRC)/firwindow.hpp \
	$(F_SRC)/firwindow_t.hpp \
	$(F_SRC)/frag.cpp \
	$(F_SRC)/frag.hpp \
	$(F_SRC)/frag_t.hpp \
	$(F_SRC)/irbase.cpp \
	$(F_SRC)/irbase.hpp \
	$(F_SRC)/irbase_t.hpp \
	$(F_SRC)/irmodel.cpp \
	$(F_SRC)/irmodel.hpp \
	$(F_SRC)/irmodel_t.hpp \
	$(F_SRC)/irmodel2.cpp \
	$(F_SRC)/irmodel2.hpp \
	$(F_SRC)/irmodel2_t.hpp \
	$(F_SRC)/irmodel2zl.cpp \
	$(F_SRC)/irmodel2zl.hpp \
	$(F_SRC)/irmodel2zl_t.hpp \
	$(F_SRC)/irmodel3.cpp \
	$(F_SRC)/irmodel3.hpp \
	$(F_SRC)/irmodel3_t.hpp \
	$(F_SRC)/irmodels.cpp \
	$(F_SRC)/irmodels.hpp \
	$(F_SRC)/irmodels_t.hpp \
	$(F_SRC)/limitmodel.cpp \
	$(F_SRC)/limitmodel.hpp \
	$(F_SRC)/limitmodel_t.hpp \
	$(F_SRC)/revbase.cpp \
	$(F_SRC)/revbase.hpp \
	$(F_SRC)/revbase_t.hpp \
	$(F_SRC)/nrev.cpp \
	$(F_SRC)/nrev.hpp \
	$(F_SRC)/nrev_t.hpp \
	$(F_SRC)/nrevb.cpp \
	$(F_SRC)/nrevb.hpp \
	$(F_SRC)/nrevb_t.hpp \
	$(F_SRC)/revmodel.cpp \
	$(F_SRC)/revmodel.hpp \
	$(F_SRC)/revmodel_t.hpp \
	$(F_SRC)/rms.cpp \
	$(F_SRC)/rms.hpp \
	$(F_SRC)/rms_t.hpp \
	$(F_SRC)/scomp.cpp \
	$(F_SRC)/scomp.hpp \
	$(F_SRC)/scomp_t.hpp \
	$(F_SRC)/slimit.cpp \
	$(F_SRC)/slimit.hpp \
	$(F_SRC)/slimit_t.hpp \
	$(F_SRC)/slot.cpp \
	$(F_SRC)/slot.hpp \
	$(F_SRC)/slot_t.hpp \
	$(F_SRC)/src.cpp \
	$(F_SRC)/src.hpp \
	$(F_SRC)/src_t.hpp \
	$(F_SRC)/stenh.cpp \
	$(F_SRC)/stenh.hpp \
	$(F_SRC)/stenh_t.hpp \
	$(F_SRC)/strev.cpp \
	$(F_SRC)/strev.hpp \
	$(F_SRC)/strev_t.hpp \
	$(F_SRC)/utils.cpp \
	$(F_SRC)/utils.hpp \
	$(F_SRC)/utils_t.hpp
