/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yinchao_media_recoder_YCPcmPlayer */

#ifndef _Included_com_yinchao_media_recoder_YCPcmPlayer
#define _Included_com_yinchao_media_recoder_YCPcmPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yinchao_media_recoder_YCPcmPlayer
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;[BLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCPcmPlayer_setDataSource
  (JNIEnv *, jobject, jstring, jbyteArray, jstring, jbyteArray);

/*
 * Class:     com_yinchao_media_recoder_YCPcmPlayer
 * Method:    start
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCPcmPlayer_start
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yinchao_media_recoder_YCPcmPlayer
 * Method:    seek
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCPcmPlayer_seek
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_yinchao_media_recoder_YCPcmPlayer
 * Method:    pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCPcmPlayer_pause
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yinchao_media_recoder_YCPcmPlayer
 * Method:    resume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCPcmPlayer_resume
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yinchao_media_recoder_YCPcmPlayer
 * Method:    stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCPcmPlayer_stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yinchao_media_recoder_YCPcmPlayer
 * Method:    setVolume
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_yinchao_media_recoder_YCPcmPlayer_setVolume
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
